---
- hosts: all
  gather_facts: false
  become: true

  vars_files:
    - vars/vault.yml
    - vars/main.yml


  tasks:
    - name: Include vagrant variables.
      include_vars:
        file: vars/vagrant_vars.yml
      when: ansible_user == 'vagrant'

    - name: Include non-vagrant variables.
      include_vars:
        file: vars/nonvagrant_vars.yml
      when: ansible_user != 'vagrant'

    - name: Check out app from Github.
      ansible.builtin.git:
        repo: "{{ git_repo }}"
        dest: "{{ node_app_location }}"
        accept_hostkey: true
        force: true
        version: HEAD
      register: app_updated

    - name: Create app config directory.
      ansible.builtin.file:
        path: "{{ node_app_location }}/config"
        state: directory
        mode: "0660"
        owner: "{{ app_user }}"
      become: true

    - name: Apply App DB config template.
      ansible.builtin.template:
        src: "{{ playbook_dir }}/templates/config.js.j2"
        dest: "{{ node_app_location }}/config/config.js"
        owner: "{{ app_user }}"
        mode: "0660"
      become: true

    - name: Set owner and groups on app files.
      ansible.builtin.command:
        cmd: "chown -R {{ app_user }}:{{ app_usr_group }} {{ node_app_location }}"
      register: perm_set
      when: app_updated and ansible_user != 'vagrant'
      become: true
      when: ansible_user != 'vagrant'

    - name: Set permissions on app files.
      ansible.builtin.command:
        cmd: "chmod -R 777 {{ node_app_location }}"
      register: perm_set
      when: app_updated and ansible_user != 'vagrant'
      become: true
      when: ansible_user != 'vagrant'

    - name: Make entry point executable.
      ansible.builtin.file:
        path: "{{ node_app_location }}/bin/index.js"
        mode: '0770'
      when: ansible_user != 'vagrant'

    - name: Install app dependencies defined in package.json.
      ansible.builtin.command:
        cmd: npm install
        chdir: "{{ node_app_location }}"
      become: true
      become_user: "{{ app_user }}"

    - name: Reload Node app using Process Manager.
      ansible.builtin.shell:
        cmd: "{{ pm2_reload_cmd }}"
        chdir: "{{ node_app_location }}"
      environment:
        NODE_ENV: "{{ node_env }}"
      become: true
      become_user: "{{ app_user }}"

    - name: Save pm2 app list/config for restore/reboot operation.
      ansible.builtin.shell:
        cmd: pm2 save
        chdir: "{{ node_app_location }}"
      become: true
      become_user: "{{ app_user }}"
      when: ansible_user != 'vagrant'
