---
- name: Check if Erlang is Installed
  ansible.builtin.command: dpkg-query -W esl-erlang
  register: erlang_check_deb
  failed_when: erlang_check_deb.rc > 1
  changed_when: erlang_check_deb.rc == 1

- name: Add erlang/elixir apt repository
  ansible.builtin.apt:
    deb: "https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb"


- name: add erlang_solutions.asc apt-key
  ansible.builtin.apt_key:
    url: "https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc"
    state: present

- name: Install erlang and elixir
  ansible.builtin.apt:
    update_cache: yes
    state: present
    pkg:
      - esl-erlang
      - elixir
      - erlang-manpages
  when: erlang_check_deb.rc == 1

- name: Install Rebar3
  ansible.builtin.get_url:
    url: https://s3.amazonaws.com/rebar3/rebar3
    dest: /usr/bin/rebar3
    mode: "0555"

- name: Install Hex
  ansible.builtin.command:
    cmd: "mix local.hex --force"
    chdir: "/home/{{ application_user }}"
  become: true
  become_user: "{{ application_user }}"
  changed_when: false

- name: Install Python pexpect package to support ansbile expect
  pip:
    name: pexpect

- name: Install Phoenix app generator
  ansible.builtin.expect:
    command: mix archive.install hex phx_new 1.5.8
    chdir: "/home/{{ application_user }}"
    responses:
      phx_new-1.5.8.ez: Y
  become: true
  become_user: "{{ application_user }}"
  changed_when: false
